name: frazile_algorithm
description: Frazile Algorithm is a open source package which provides users the most popular & commonly used algorithms in popular companies Google, Facebook, Instagram, WhatsApp.
version: 2.0.0
homepage: https://github.com/FrazileDevelopers/Frazile_Algorithm

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # assets:
  #   - images/

  # fonts:
  #   - family: Google
  #     fonts:
  #       - asset: fonts/google-Regular.ttf
  #       - asset: fonts/google-Italic.ttf
  #         style: italic